"""Pydantic v2 event models — the contract between every Agent Pulsar component.

All messages on the event bus are serialized from these models. Every field
has a sensible default so callers only need to provide the required fields.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field

from agent_pulsar.schemas.enums import (
    ComplexityTier,
    ExecutionTier,
    Priority,
    TaskStatus,
)


# ---------------------------------------------------------------------------
# Supporting models
# ---------------------------------------------------------------------------


class RetryPolicy(BaseModel):
    """How many times to retry a failed task and which backoff strategy to use."""

    model_config = ConfigDict(frozen=True)

    max_retries: int = 3
    backoff: str = "exponential"  # "exponential" | "fixed"
    base_delay_ms: int = 1000


# ---------------------------------------------------------------------------
# Event bus messages
# ---------------------------------------------------------------------------


class TaskRequest(BaseModel):
    """High-level request from OpenClaw skill — before decomposition.

    Published to: task.submitted
    """

    model_config = ConfigDict(frozen=True)

    request_id: UUID = Field(default_factory=uuid4)
    user_id: str
    conversation_id: str
    intent: str
    raw_message: str
    params: dict[str, Any] = Field(default_factory=dict)
    priority: Priority = Priority.NORMAL
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class AtomicTask(BaseModel):
    """Single decomposed sub-task for worker execution.

    Published to: task.backlog.<skill_type>
    """

    model_config = ConfigDict(frozen=True)

    task_id: UUID = Field(default_factory=uuid4)
    request_id: UUID
    user_id: str
    conversation_id: str
    type: str  # e.g. "email.send", "research.summarize"
    params: dict[str, Any] = Field(default_factory=dict)
    priority: Priority = Priority.NORMAL
    dependencies: list[UUID] = Field(default_factory=list)
    credential_ref: str | None = None  # Phase 2 — Vault secret reference
    execution_tier: ExecutionTier = ExecutionTier.HOT
    model_assignment: str = "claude-haiku-4-5-20250414"
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    timeout_ms: int = 300_000  # 5 minutes default
    retry_policy: RetryPolicy = Field(default_factory=RetryPolicy)


class TaskResult(BaseModel):
    """Result of a worker executing an AtomicTask.

    Published to: task.results
    """

    model_config = ConfigDict(frozen=True)

    task_id: UUID
    request_id: UUID
    status: TaskStatus
    output: dict[str, Any] = Field(default_factory=dict)
    error: str | None = None
    model_used: str | None = None
    execution_tier_used: ExecutionTier | None = None
    duration_ms: int = 0
    retry_count: int = 0
    completed_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class TaskStatusUpdate(BaseModel):
    """Status change notification for a task.

    Published to: task.status
    """

    model_config = ConfigDict(frozen=True)

    task_id: UUID
    request_id: UUID
    status: TaskStatus
    updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    retry_count: int = 0
    error: str | None = None


class CompletionEvent(BaseModel):
    """Emitted when ALL tasks for a request are terminal (COMPLETED or FAILED).

    Published to: task.completed
    Triggers: OpenClaw webhook callback to deliver results to user.
    """

    model_config = ConfigDict(frozen=True)

    request_id: UUID
    user_id: str
    conversation_id: str
    status: TaskStatus  # Overall: COMPLETED if all succeeded, FAILED if any failed
    summary: str  # Human-readable summary generated by Haiku
    results: list[TaskResult] = Field(default_factory=list)
    total_cost_usd: float = 0.0
    total_duration_ms: int = 0
    completed_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
