"""initial schema

Revision ID: c20f81597fbf
Revises: 
Create Date: 2026-03-19 13:01:52.641416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20f81597fbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_requests',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=False),
    sa.Column('intent', sa.String(length=255), nullable=False),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_task_requests_status'), 'task_requests', ['status'], unique=False)
    op.create_index(op.f('ix_task_requests_user_id'), 'task_requests', ['user_id'], unique=False)
    op.create_table('atomic_tasks',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('execution_tier', sa.String(length=10), nullable=False),
    sa.Column('model_assignment', sa.String(length=100), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['task_requests.request_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_atomic_tasks_request_id'), 'atomic_tasks', ['request_id'], unique=False)
    op.create_index(op.f('ix_atomic_tasks_status'), 'atomic_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_atomic_tasks_type'), 'atomic_tasks', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atomic_tasks_type'), table_name='atomic_tasks')
    op.drop_index(op.f('ix_atomic_tasks_status'), table_name='atomic_tasks')
    op.drop_index(op.f('ix_atomic_tasks_request_id'), table_name='atomic_tasks')
    op.drop_table('atomic_tasks')
    op.drop_index(op.f('ix_task_requests_user_id'), table_name='task_requests')
    op.drop_index(op.f('ix_task_requests_status'), table_name='task_requests')
    op.drop_table('task_requests')
    # ### end Alembic commands ###
